### ISSUE TITLE
images to Pixen format and added layers to represent lane markings and cars

### ISSUE THREAD

**Issue by pearlpeiwenhuang** [ericlavigne/CarND-Detect-Lane-Lines-And-Vehicles#1]
While you mention below, I was trying to make one for my own data. However, I couldn't find a way like your precise marked on lane and car. Would you please show some tips for it?

"I copied each of these images to the training directory, for annotation. I converted the images to Pixen format, added layers to represent lane markings and cars, and created image masks in those layers to indicate the locations of lane markings and cars. I saved each layer separately with filenames ending in "x", "lanes", and "cars" so they could easily be imported into Python for training convolutional neural networks."

**Comment by ericlavigne** [comment]
Added tips for annotation accuracy in this commit:

https://github.com/ericlavigne/CarND-Detect-Lane-Lines-And-Vehicles/commit/c0012106c1dd6d3cbeda50793f80070bf80e9db8

Does this adequately address your question? If not, please clarify what kind of problem you are having.

**Comment by pearlpeiwenhuang** [comment]
Thank you for the reply.
Sorry that I was on the vacation and didn't reply earlier and I didn't express my problem more precisely.
My real problem is that the lane and car of my dataset is from video game (more like cartoon). Therefore, it's harder to find the lane line(actually no lane lines on some scenes). I tried to use a lot opencv functions to extract lanes and objects but it doesn't work as good as yours.
Anyway, thank you so much for the reply and sharing.
