### ISSUE TITLE
Where Can I Set the Batch Size?

### ISSUE THREAD

**Issue by ColeKOP** [ericlavigne/CarND-Detect-Lane-Lines-And-Vehicles#2]
Hi,

Thank you for the sharing. May I know how I can set the batch size since it will run out of memory if more images are trained. Thank you.

**Comment by ericlavigne** [comment]
This project had a small number of images and didn't require batching. If you are using a lot of images, you will need to use "fit_generator" and a python generator to avoid keeping all images in memory.

https://keras.io/models/sequential/https://medium.com/@fromtheast/implement-fit-generator-in-keras-61aa2786ce98

This is a question about how to use Keras, and not a problem with this project, so I am closing the issue now.
